name: preview

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "content/**"
      - "themes/**"
      - pelicanconf.py

env:
  PYTHON_VERSION: 3.8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run pelican content
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "output/"
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
